### ISSUE TITLE
Error in Apache cookbook .kitchen.yml

### ISSUE THREAD

**Issue by dm4r** [scarolan/chef-essentials-answerkey#1]
Update answer key to ensure that the cookbooks/apache/.kitchen.yml driver is docker NOT:

```
---
driver:
  name: apache
```

**Comment by scarolan** [comment]
This should be fixed now.  I also stripped all the tags from the repo, and moved slide numbers into the commit messages.  Having tags made rebasing basically impossible, because when you rebase, you get new commit hashes which messed up the tags.  

So now you just have to 'git log --oneline' to see which commit you want to revert to.
